version: '3.4'

services:
  codeflix.catalog.db:
    container_name: catalogdb
    hostname: catalogdb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: c0d3fl1x#